# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whisper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rwhisper.proto\"=\n\x16LocalTranscribeRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x15\n\x05model\x18\x02 \x01(\x0e\x32\x06.Model\"\'\n\x17LocalTranscribeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t*t\n\x05Model\x12\x08\n\x04TINY\x10\x00\x12\x08\n\x04\x42\x41SE\x10\x01\x12\t\n\x05SMALL\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\t\n\x05LARGE\x10\x04\x12\x0b\n\x07TINY_EN\x10\x05\x12\x0b\n\x07\x42\x41SE_EN\x10\x06\x12\x0c\n\x08SMALL_EN\x10\x07\x12\r\n\tMEDIUM_EN\x10\x08\x32Q\n\x07Whisper\x12\x46\n\x0fLocalTranscribe\x12\x17.LocalTranscribeRequest\x1a\x18.LocalTranscribeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whisper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODEL._serialized_start=121
  _MODEL._serialized_end=237
  _LOCALTRANSCRIBEREQUEST._serialized_start=17
  _LOCALTRANSCRIBEREQUEST._serialized_end=78
  _LOCALTRANSCRIBERESPONSE._serialized_start=80
  _LOCALTRANSCRIBERESPONSE._serialized_end=119
  _WHISPER._serialized_start=239
  _WHISPER._serialized_end=320
# @@protoc_insertion_point(module_scope)
