# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import whisper_pb2 as whisper__pb2


class WhisperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LocalTranscribe = channel.unary_unary(
                '/Whisper/LocalTranscribe',
                request_serializer=whisper__pb2.LocalTranscribeRequest.SerializeToString,
                response_deserializer=whisper__pb2.LocalTranscribeResponse.FromString,
                )


class WhisperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LocalTranscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WhisperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LocalTranscribe': grpc.unary_unary_rpc_method_handler(
                    servicer.LocalTranscribe,
                    request_deserializer=whisper__pb2.LocalTranscribeRequest.FromString,
                    response_serializer=whisper__pb2.LocalTranscribeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Whisper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Whisper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LocalTranscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Whisper/LocalTranscribe',
            whisper__pb2.LocalTranscribeRequest.SerializeToString,
            whisper__pb2.LocalTranscribeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
