name: Compile client binary

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - name: Install pipenv
        run: |
          python -m pip install pipenv
      - name: Install project dependencies
        run: |
          pipenv install
      - name: Install pyinstaller
        run: |
          pipenv run pip install pyinstaller
      - name: Compile client binary
        run: |
          pipenv run pyinstaller whisper/client.py --onefile
